apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
  name: vault
  namespace: openshift-gitops
spec:
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks/replicas
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  source:
    path: vault
    repoURL: https://github.com/gurnben/vault-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: vault-agent-injector-cfg
    jsonPointers:
      - /webhooks/0/clientConfig/caBundle         
